### ISSUE TITLE
Web page

### ISSUE THREAD

**Issue by oganm** [hackseq/2016_project_7#36]
The app is currently live on https://oganm.shinyapps.io/2016_project_7/. I added files required for a github page. If @gracezheng adds me as a contributor I can open the site as https://hackseq.github.io/2016_project_7/ or we can change the repo name to vasco

**Comment by gracezheng** [comment]
@oganm I added you as a collaborator, and renamed the repo to vasco.

Can we hold off from major changes until we figure out the steps forward as a group (I just sent out an email earlier)?

**Comment by oganm** [comment]
Huh interesting. Still cannot  see the settings page. I guess that's for the owner. If you click the settings and go down to GitHub Pages section, you can select to host it from master branch docs folder. that will make it available from https://hackseq.github.io/vasco/  now

**Comment by gracezheng** [comment]
ok, updated it. Let me know if it is ok.

**Comment by oganm** [comment]
yap seems to be working
