### ISSUE TITLE
Create new group by selecting bug ~ln 160 in server.R

### ISSUE THREAD

**Issue by esmason** [hackseq/2016_project_7#37]
Weird bug where some cells (about 5 cells in our data) would not be included in the new group even though I saw that the cells' `x` `y` were in `selected_data_toRename()` and were the same as the `tSNE_1` and `tSNE_2` in `rValues$tsne` data.  I tested by trying to make 1 big group but those cells were still not included.

anyway I fixed it by rounding to 5 decimal places (Which shouldn't change the data!?) and now it works.

**Comment by esmason** [comment]
fixed

**Comment by oganm** [comment]
Yeah I was aware of this when implementing it. Rounding should be fine in most cases. Ideally we would find why IDs don't work but whatever works...

**Comment by esmason** [comment]
to be clear:
the cells have the exact same x and y coords (and that is what we are comparing to find which cells to re-group). it's weird that it worked for 99.9% of cells without rounding

I'm not sure if you thought I was referring to the incorrect dna barcodes problem we identified during the hackathon, which is a separate issue

**Comment by oganm** [comment]
I know I know. Barcodes was the reason I used coordinate matching remember? And when implementing that I noticed not all selected cells were actually selected. It is indeed weird but not really unexpected as computers aren't that good at counting floating numbers
