### ISSUE TITLE
differential gene expression table?

### ISSUE THREAD

**Issue by gracezheng** [hackseq/2016_project_7#40]
@oganm In the most recent version, I do not see the differential gene table any more. Did you remove it for some reason?

**Comment by esmason** [comment]
@gracezheng I occasionally cannot see the table too (I have no idea why).

I can currently see it on the most recent version.

**Comment by oganm** [comment]
It sometimes disappears. One of the recurring problems like the apperance of uber-narrow plots. Not sure how to solve right now
